# demo 数据预处理之均值移除

In [11]:
import numpy as np
import sklearn.preprocessing as sp

In [13]:
raw_samples = np.array([
    [23, 2, 10000],
    [21, 1, 9000],
    [40, 18, 10500]])
r = sp.scale(raw_samples)
r

array([[-0.58654642, -0.64194074,  0.26726124],
       [-0.82116498, -0.77032889, -1.33630621],
       [ 1.4077114 ,  1.41226963,  1.06904497]])

In [14]:
print(r.mean(axis=0))
print(r.std(axis=0))

[ 0.00000000e+00  7.40148683e-17 -9.62193288e-16]
[1. 1. 1.]
